/* Autogenerated source */

extern void fopen;
extern void freopen;
extern void fflush;
extern void fclose;
extern void remove;
extern void rename;
extern void tmpfile;
extern void setvbuf;
extern void setbuf;
extern void fprintf;
extern void printf;
extern void sprintf;
extern void vfprintf;
extern void vprintf;
extern void vsprintf;
extern void fscanf;
extern void scanf;
extern void sscanf;
extern void fgetc;
extern void fgets;
extern void fputc;
extern void fputs;
extern void ungetc;
extern void fread;
extern void fwrite;
extern void fgetpos;
extern void fseek;
extern void fsetpos;
extern void ftell;
extern void rewind;
extern void clearerr;
extern void feof;
extern void ferror;
extern void perror;
extern void atof;
extern void atoi;
extern void atol;
extern void strtod;
extern void strtol;
extern void strtoul;
extern void wcstombs;
extern void wctomb;
extern void mblen;
extern void mbstowcs;
extern void mbtowc;
extern void rand;
extern void srand;
extern void calloc;
extern void malloc;
extern void realloc;
extern void free;
extern void abort;
extern void exit;
extern void atexit;
extern void system;
extern void getenv;
extern void bsearch;
extern void qsort;
extern void abs;
extern void labs;
extern void div;
extern void ldiv;
extern void memchr;
extern void memcmp;
extern void memcpy;
extern void memmove;
extern void memset;
extern void strcat;
extern void strchr;
extern void strcmp;
extern void strcoll;
extern void strcpy;
extern void strcspn;
extern void strerror;
extern void strlen;
extern void strncat;
extern void strncmp;
extern void strncpy;
extern void strpbrk;
extern void strrchr;
extern void strspn;
extern void strstr;
extern void strtok;
extern void strxfrm;
extern void sin;
extern void cos;
extern void tan;
extern void sinh;
extern void cosh;
extern void tanh;
extern void asin;
extern void acos;
extern void atan;
extern void atan2;
extern void exp;
extern void log;
extern void log10;
extern void pow;
extern void sqrt;
extern void ceil;
extern void floor;
extern void fabs;
extern void ldexp;
extern void frexp;
extern void modf;
extern void fmod;
extern void creal;
extern void cimag;
extern void carg;
extern void cabs;
extern void cacos;
extern void casin;
extern void catan;
extern void ccos;
extern void csin;
extern void ctan;
extern void cacosh;
extern void casinh;
extern void catanh;
extern void ccosh;
extern void csinh;
extern void ctanh;
extern void cexp;
extern void clog;
extern void cpow;
extern void csqrt;
extern void cproj;
extern void crealf;
extern void cimagf;
extern void cargf;
extern void cabsf;
extern void cacosf;
extern void casinf;
extern void catanf;
extern void ccosf;
extern void csinf;
extern void ctanf;
extern void cacoshf;
extern void casinhf;
extern void catanhf;
extern void ccoshf;
extern void csinhf;
extern void ctanhf;
extern void cexpf;
extern void clogf;
extern void cpowf;
extern void csqrtf;
extern void cprojf;
extern void isalnum;
extern void isalpha;
extern void iscntrl;
extern void isdigit;
extern void isgraph;
extern void islower;
extern void isupper;
extern void isprint;
extern void ispunct;
extern void isspace;
extern void isxdigit;
extern void tolower;
extern void toupper;
extern void feclearexcept;
extern void fegetexceptflag;
extern void fesetexceptflag;
extern void fetestexcept;
extern void fegetround;
extern void fesetround;
extern void fegetenv;
extern void fesetenv;
extern void feholdexcept;
extern void signal;
extern void raise;
extern void clock;
extern void difftime;
extern void mktime;
extern void time;
extern void asctime;
extern void ctime;
extern void gmtime;
extern void localtime;
extern void strftime;
extern void fwprintf;
extern void fwscanf;
extern void swprintf;
extern void swscanf;
extern void vfwprintf;
extern void vfwscanf;
extern void vswprintf;
extern void vswscanf;
extern void vwprintf;
extern void vwscanf;
extern void wprintf;
extern void wscanf;
extern void fgetwc;
extern void fgetws;
extern void fputwc;
extern void fputws;
extern void fwide;
extern void getwc;
extern void getwchar;
extern void putwchar;
extern void ungetwc;
extern void wcstod;
extern void wcstof;
extern void wcstold;
extern void wcstol;
extern void wcstoll;
extern void wcstoul;
extern void wcstoull;
extern void wcscpy;
extern void wcsncpy;
extern void wmemcpy;
extern void wmemmove;
extern void wcscat;
extern void wcsncat;
extern void wcscmp;
extern void wcscoll;
extern void wcsncmp;
extern void wcsxfrm;
extern void wmemcmp;
extern void wcschr;
extern void wcscspn;
extern void wcspbrk;
extern void wcsspn;
extern void wcsstr;
extern void wcstok;
extern void wmemchr;
extern void wcslen;
extern void wmemset;
extern void wcsftime;
extern void mbsinit;
extern void iswalnum;
extern void iswalpha;
extern void iswcntrl;
extern void iswdigit;
extern void iswgraph;
extern void iswlower;
extern void iswupper;
extern void iswprint;
extern void iswpunct;
extern void iswspace;
extern void iswxdigit;
extern void towlower;
extern void towupper;

int bs1_cc_imptab_cnt=244;

char *bs1_cc_imptab_strs[]={
"fopen", "freopen", "fflush", "fclose", "remove", "rename", "tmpfile", 
"setvbuf", "setbuf", "fprintf", "printf", "sprintf", "vfprintf", 
"vprintf", "vsprintf", "fscanf", "scanf", "sscanf", "fgetc", "fgets", 
"fputc", "fputs", "ungetc", "fread", "fwrite", "fgetpos", "fseek", 
"fsetpos", "ftell", "rewind", "clearerr", "feof", "ferror", "perror", 
"atof", "atoi", "atol", "strtod", "strtol", "strtoul", "wcstombs", 
"wctomb", "mblen", "mbstowcs", "mbtowc", "rand", "srand", "calloc", 
"malloc", "realloc", "free", "abort", "exit", "atexit", "system", 
"getenv", "bsearch", "qsort", "abs", "labs", "div", "ldiv", "memchr", 
"memcmp", "memcpy", "memmove", "memset", "strcat", "strchr", "strcmp", 
"strcoll", "strcpy", "strcspn", "strerror", "strlen", "strncat", 
"strncmp", "strncpy", "strpbrk", "strrchr", "strspn", "strstr", "strtok", 
"strxfrm", "sin", "cos", "tan", "sinh", "cosh", "tanh", "asin", "acos", 
"atan", "atan2", "exp", "log", "log10", "pow", "sqrt", "ceil", "floor", 
"fabs", "ldexp", "frexp", "modf", "fmod", "creal", "cimag", "carg", 
"cabs", "cacos", "casin", "catan", "ccos", "csin", "ctan", "cacosh", 
"casinh", "catanh", "ccosh", "csinh", "ctanh", "cexp", "clog", "cpow", 
"csqrt", "cproj", "crealf", "cimagf", "cargf", "cabsf", "cacosf", 
"casinf", "catanf", "ccosf", "csinf", "ctanf", "cacoshf", "casinhf", 
"catanhf", "ccoshf", "csinhf", "ctanhf", "cexpf", "clogf", "cpowf", 
"csqrtf", "cprojf", "isalnum", "isalpha", "iscntrl", "isdigit", "isgraph", 
"islower", "isupper", "isprint", "ispunct", "isspace", "isxdigit", 
"tolower", "toupper", "feclearexcept", "fegetexceptflag", 
"fesetexceptflag", "fetestexcept", "fegetround", "fesetround", "fegetenv", 
"fesetenv", "feholdexcept", "signal", "raise", "clock", "difftime", 
"mktime", "time", "asctime", "ctime", "gmtime", "localtime", "strftime", 
"fwprintf", "fwscanf", "swprintf", "swscanf", "vfwprintf", "vfwscanf", 
"vswprintf", "vswscanf", "vwprintf", "vwscanf", "wprintf", "wscanf", 
"fgetwc", "fgetws", "fputwc", "fputws", "fwide", "getwc", "getwchar", 
"putwchar", "ungetwc", "wcstod", "wcstof", "wcstold", "wcstol", "wcstoll", 
"wcstoul", "wcstoull", "wcscpy", "wcsncpy", "wmemcpy", "wmemmove", 
"wcscat", "wcsncat", "wcscmp", "wcscoll", "wcsncmp", "wcsxfrm", "wmemcmp", 
"wcschr", "wcscspn", "wcspbrk", "wcsspn", "wcsstr", "wcstok", "wmemchr", 
"wcslen", "wmemset", "wcsftime", "mbsinit", "iswalnum", "iswalpha", 
"iswcntrl", "iswdigit", "iswgraph", "iswlower", "iswupper", "iswprint", 
"iswpunct", "iswspace", "iswxdigit", "towlower", "towupper", (char *)0};

void *bs1_cc_imptab_ptrs[]={
&fopen, &freopen, &fflush, &fclose, &remove, &rename, &tmpfile, &setvbuf, 
&setbuf, &fprintf, &printf, &sprintf, &vfprintf, &vprintf, &vsprintf, 
&fscanf, &scanf, &sscanf, &fgetc, &fgets, &fputc, &fputs, &ungetc, &fread, 
&fwrite, &fgetpos, &fseek, &fsetpos, &ftell, &rewind, &clearerr, &feof, 
&ferror, &perror, &atof, &atoi, &atol, &strtod, &strtol, &strtoul, 
&wcstombs, &wctomb, &mblen, &mbstowcs, &mbtowc, &rand, &srand, &calloc, 
&malloc, &realloc, &free, &abort, &exit, &atexit, &system, &getenv, 
&bsearch, &qsort, &abs, &labs, &div, &ldiv, &memchr, &memcmp, &memcpy, 
&memmove, &memset, &strcat, &strchr, &strcmp, &strcoll, &strcpy, &strcspn, 
&strerror, &strlen, &strncat, &strncmp, &strncpy, &strpbrk, &strrchr, 
&strspn, &strstr, &strtok, &strxfrm, &sin, &cos, &tan, &sinh, &cosh, 
&tanh, &asin, &acos, &atan, &atan2, &exp, &log, &log10, &pow, &sqrt, 
&ceil, &floor, &fabs, &ldexp, &frexp, &modf, &fmod, &creal, &cimag, &carg, 
&cabs, &cacos, &casin, &catan, &ccos, &csin, &ctan, &cacosh, &casinh, 
&catanh, &ccosh, &csinh, &ctanh, &cexp, &clog, &cpow, &csqrt, &cproj, 
&crealf, &cimagf, &cargf, &cabsf, &cacosf, &casinf, &catanf, &ccosf, 
&csinf, &ctanf, &cacoshf, &casinhf, &catanhf, &ccoshf, &csinhf, &ctanhf, 
&cexpf, &clogf, &cpowf, &csqrtf, &cprojf, &isalnum, &isalpha, &iscntrl, 
&isdigit, &isgraph, &islower, &isupper, &isprint, &ispunct, &isspace, 
&isxdigit, &tolower, &toupper, &feclearexcept, &fegetexceptflag, 
&fesetexceptflag, &fetestexcept, &fegetround, &fesetround, &fegetenv, 
&fesetenv, &feholdexcept, &signal, &raise, &clock, &difftime, &mktime, 
&time, &asctime, &ctime, &gmtime, &localtime, &strftime, &fwprintf, 
&fwscanf, &swprintf, &swscanf, &vfwprintf, &vfwscanf, &vswprintf, 
&vswscanf, &vwprintf, &vwscanf, &wprintf, &wscanf, &fgetwc, &fgetws, 
&fputwc, &fputws, &fwide, &getwc, &getwchar, &putwchar, &ungetwc, &wcstod, 
&wcstof, &wcstold, &wcstol, &wcstoll, &wcstoul, &wcstoull, &wcscpy, 
&wcsncpy, &wmemcpy, &wmemmove, &wcscat, &wcsncat, &wcscmp, &wcscoll, 
&wcsncmp, &wcsxfrm, &wmemcmp, &wcschr, &wcscspn, &wcspbrk, &wcsspn, 
&wcsstr, &wcstok, &wmemchr, &wcslen, &wmemset, &wcsftime, &mbsinit, 
&iswalnum, &iswalpha, &iswcntrl, &iswdigit, &iswgraph, &iswlower, 
&iswupper, &iswprint, &iswpunct, &iswspace, &iswxdigit, &towlower, 
&towupper, (void *)0};

